server.port=8081
spring.application.name=notification-service


# MAIL SERVICE
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a86be9001@smtp-brevo.com
spring.mail.password=xsmtpsib-a7607df111f535899e21428e03eca89c0de321478f0c7c0145526bd3e2f2c195-sXkmcZDILdAtexoo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000




# LOGGING
# ===========================
logging.level.com.claudev.notification=DEBUG
logging.level.org.springframework.mail=DEBUG