server.port=8081
spring.application.name=notification-service

# --- MAIL CONFIG (Mailtrap) ---
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f8d4e886aebb36
spring.mail.password=42aca171325fd2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true