spring.application.name=digital-agenda-private

spring.datasource.url=jdbc:mysql://localhost:3306/agenda_db?serverTmezone=UTC
spring.datasource.username=claudev
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# lascio decidere a spring quale versione di hibernate utilizzare per evitare eventuali problemi di  incompatibilita' tra le versioni

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# Imposta il prefisso globale per tutti gli endpoint Spring Data REST
spring.data.rest.base-path=/api

# aggiorna e ricrea i dati (Quelli del Data Loader : Command Liner) nel database
# Se le TABELLE non esistono, creale. Se esistono ma mancano colonne, aggiungile
spring.jpa.hibernate.ddl-auto=update

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=881111884550-3ao8ps618d05fp9uoqol60fjc0763a44.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile


