spring.application.name=digital-agenda-private


# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.properties.hibernate.show_sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# SPRING DATA REST
spring.data.rest.base-path=/api


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:36000000}


# OAUTH2 GOOGLE
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile


# LOGGING
logging.level.com.claudev.agenda=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO

# MONITORAGGIO GRAFANA , PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true