spring.application.name=digital-agenda-private


# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.properties.hibernate.show_sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# SPRING DATA REST
spring.data.rest.base-path=/api


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:36000000}


# OAUTH2 GOOGLE
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile


# LOGGING
logging.level.com.claudev.agenda=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO

# MONITORAGGIO GRAFANA E PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

# Variabili custom per gestire il CORS e i redirect OAuth dinamicamente.
# RICORDA sulla vps ci pensera docker-compose a fare la magia
#app.allowed-origins=${APP_ALLOWED_ORIGINS:http://localhost:4200}
#app.frontend-url=${APP_FRONTEND_URL:http://localhost:4200}
app.frontend-url=https://digital-agenda.it

# Diciamo a Spring di fidarsi del Proxy (Traefik) per ricostruire gli URL corretti
#server.forward-headers-strategy=native -> non ha funzionato

# in produzione diciamo a spring di accettare qualsiasi header dal proxy traefik
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.use-relative-redirects=true

# Forza URL di base di OAuth
#spring.security.oauth2.client.registration.google.redirect-uri=https://api.${DOMAIN}/login/oauth2/code/google

