
# DA UTILIZARE SOLO IN LOCALE

spring.application.name=digital-agenda-private

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/agenda_db?serverTmezone=UTC
spring.datasource.username=claudev
spring.datasource.password=D3v3l0p3r.26>
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# SPRING DATA REST
spring.data.rest.base-path=/api

# JWT
jwt.secret=questa_e_una_chiave_segreta_molto_lunga_e_complicata_che_serve_per_superare_i_test_di_sicurezza_2026
jwt.expiration=36000000

# OAuth2 Google Configuration -- SE UTILIZZI GOOGLE (MA PUOI ANCHE EVITARLO) DEVI INSERIRIE DI NUOVO IL LOCALHOST SU GOOGLE CLOUD
spring.security.oauth2.client.registration.google.client-id=881111884550-3ao8ps618d05fp9uoqol60fjc0763a44.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# MONITORAGGIO GRAFANA E PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

# CORS
app.allowed-origins=${APP_ALLOWED_ORIGINS:http://localhost:4200}

# FRONTEND
app.frontend-url=${APP_FRONTEND_URL:http://localhost:4200}


