events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            # magia per le app Angular (SPA)
            # Se un file non esiste, reindirizza sempre a index.html
            try_files $uri $uri/ /index.html;
        }

        # Cache dei file statici per migliorare le performance
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1y;
            add_header Cache-Control "public, no-transform";
        }
    }
}