-- MySQL Script generated by MySQL Workbench
-- Thu Feb 19 22:10:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agenda_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `agenda_db` ;

-- -----------------------------------------------------
-- Table `agenda_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_db`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `job_title` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `on_site` BIT(1) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `profile_photo` VARCHAR(64) NULL DEFAULT NULL,
  `remote` BIT(1) NOT NULL,
  `role` ENUM('ADMIN', 'CUSTOMER', 'PROFESSIONAL') NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `vat_registration_number` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UKr43af9ap4edm43mmtq01oddj6` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agenda_db`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_db`.`appointments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `appointment_date_time` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `duration_minutes` INT NULL DEFAULT NULL,
  `notes` VARCHAR(500) NULL DEFAULT NULL,
  `status` ENUM('CANCELLED', 'COMPLETED', 'CONFIRMED', 'PENDING', 'REJECTED') NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `customer_id` BIGINT NOT NULL,
  `professional_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK4q5rt20vvnkv7eohwq22l3ayy` (`customer_id` ASC) VISIBLE,
  INDEX `FK9s7d43fdta7c8kcgskd4wadlq` (`professional_id` ASC) VISIBLE,
  CONSTRAINT `FK4q5rt20vvnkv7eohwq22l3ayy`
    FOREIGN KEY (`customer_id`)
    REFERENCES `agenda_db`.`users` (`id`),
  CONSTRAINT `FK9s7d43fdta7c8kcgskd4wadlq`
    FOREIGN KEY (`professional_id`)
    REFERENCES `agenda_db`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agenda_db`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_db`.`payment_methods` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `details` VARCHAR(255) NULL DEFAULT NULL,
  `method_type` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKin7rtmim3ljrrhh5kxbq27s2v` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKin7rtmim3ljrrhh5kxbq27s2v`
    FOREIGN KEY (`user_id`)
    REFERENCES `agenda_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agenda_db`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_db`.`schedules` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `day_of_week` ENUM('FRIDAY', 'MONDAY', 'SATURDAY', 'SUNDAY', 'THURSDAY', 'TUESDAY', 'WEDNESDAY') NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `end_time` TIME NOT NULL,
  `start_time` TIME NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKd4y4xekwahv9boo6lc8gfl3jv` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKd4y4xekwahv9boo6lc8gfl3jv`
    FOREIGN KEY (`user_id`)
    REFERENCES `agenda_db`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
