# Usa SOLO Java, niente Maven, perché il JAR lo hai già buildato nella pipeline!
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# Copia il jar compilato dalla cartella target
# NOTA: assicurati che il nome del file corrisponda a quello generato dal tuo pom.xml!
COPY target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]