name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/digital-agenda
          
          # Scarica le nuove modifiche
          git pull origin main
          
          # Forza la ricreazione del database per fargli prendere le nuove porte
          docker compose up -d --force-recreate db
          
          # Poi lancia il comando normale per gli altri servizi
          docker compose up -d --build --remove-orphans
          
          docker image prune -f